apitoken: <put your SmartThings API token here>
monitor:
  - light
  - temperatureMeasurement
  - illuminanceMeasurement
  - relativeHumidityMeasurement
  - ultravioletIndex
  - battery
  - powerMeter
  - thermostatOperatingState
  - contactSensor
  - energyMeter
  - lock
  - motionSensor
  - waterSensor
  - valve
  - switch
  - switchLevel
  - temperature
  - presenceSensor
  - voltageMeasurement
period: 120
influxurl: http://localhost:8086
influxuser: user
influxpassword: password
influxdatabase: database
valuemap:
  switch: 
    off: 0
    on: 1