apitoken: < YOUR API TOKEN HERE> 
monitor:
  - light
  - temperatureMeasurement
  - illuminanceMeasurement
  - relativeHumidityMeasurement
  - ultravioletIndex
  - battery
  - powerMeter
  - thermostatOperatingState
  - contactSensor
  - energyMeter
  - lock
  - motionSensor
  - waterSensor
  - valve
  - switch
  - switchLevel
  - temperature
  - presenceSensor
  - voltageMeasurement
ignoredvalues:
  - supportedLockValues
  - supportedUnlockDirections
  - supportedLockCommands
  - levelRange
  - temperatureRange 
  - quantity
  - type
period: 120
influxurl: http://influxdb:8086
influxuser: username
influxpassword: password
influxdatabase: smartthings
valuemap:
  switch:
    off: 0
    on: 1
  presence:
    present: 1
    not present: 0
  water:
    wet: 1
    dry: 0
  motion:
    active: 1
    inactive: 0
  thermostatOperatingState:
    heating: 1
    cooling: 1
    idle: 0
  lock:
    locked: 1
    unlocked: 0
  contact:
    closed: 0
    open: 1
  windowShade:
    closed: 0
    open: 1
  door:
    closed: 1
    open: 0
    opening: 0
    closing: 0
    unknown: 0