version: '2'
services:
  monitor:
    image: gcndevelopment/smartthings-influx:latest
    environment:
      - APITOKEN
    volumes:
      - ./docker-compose-config.yaml:/.smartthings-influx.yaml
    command: monitor
