apitoken: <put your smartthings api token here>
monitor:
  - light
  - temperatureMeasurement
  - illuminanceMeasurement
  - relativeHumidityMeasurement
  - ultravioletIndex
  - battery
  - powerMeter
  - thermostatOperatingState
  - contactSensor
  - energyMeter
  - lock
  - motionSensor
  - waterSensor
  - valve
  - switch
  - switchLevel
  - temperature
  - presenceSensor
  - voltageMeasurement
period: 120
influxurl: http://influxdb:8086
influxuser: admin
influxpassword: password
influxdatabase: SmartThings
valuemap:
  switch: 
    off: 0
    on: 1